export enum TOOLS_APP_ROUTES {
  HOME = '/',
  ADD_ADVERTS = '/add-adverts',
  LOGIN = '/login',
  PROFILE = '/profile',
  MY_PROFILE = '/profile/me',
  MESSAGES = '/profile/messages',
  MY_ADVERTS = '/profile/my-adverts',
  CHANGE_ADVERTS = '/profile/my-adverts/change-advert',
  FAVOURITES = '/profile/favourites',
  RENTED_TOOLS = '/profile/rented-tools',
  FIND_USERS = '/profile/find-users',
  CATEGORY = '/profile/category',
  CATEGORIES = '/api/categories',
  HELP = '/help',
  ADVERTISING = '/advertising',
  ABOUT_US = '/about-us',
  CONTACTS = '/contacts',
  PRIVACY_POLICY = 'privacy-policy',
  CONDITIONS = '/conditions',
  IMPRINT = '/imprint',
  SOCIAL_MEDIA = '/medias',
  NOT_FOUND = '*',
  TOOLS = '/tools',
  SEARCH_RESULTS = '/search-results',
  CHANGE_USER = '/profile/change-user',
}
